### ISSUE TITLE
Alt attribuut

### ISSUE THREAD

**Issue by Mossati** [Karima002/your-tribe-profile-card#4]
Maak gebruik van een alt attribuut in je IMG tag, dit zorgt ervoor dat wanneer je afbeelding niet kan inladen dat de alt wordt ingeladen.
Het maakt ook je website meer toegankelijk.

Link:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img

**Comment by Karima002** [comment]
Opgelost! Thanks voor je feedback
